# -*- coding: utf-8 -*-
"""Temperature calc for multicomponent systems

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9Y_Se_XwdtgHTmICxuRAu8Zl6mW0s8B

Definiendo la sustancia
"""

Sustancia = str(input('Ingrese la sustancia a trabajar: '))
Sus_Confirm = input(f'¿La sustancia a trabajar es {Sustancia}? (y/n)')
if Sus_Confirm == 'n':
  while Sus_Confirm == 'n':
    if Sus_Confirm == 'n':
      Sustancia = str(input('Ingrese la sustancia a trabajar: '))
      Sus_Confirm = input(f'¿La sustancia a trabajar es {Sustancia}? (y/n)')
    if Sus_Confirm == 'y':
      print(f'Sustancia confirmada')
if Sus_Confirm == 'y':
  print(f'Sustancia confirmada')

"""Definiendo las constantes A,B,C y D"""

A = float(input('Ingrese el valor de A en notación científica(5E+2) o general(500): '))

A_Confirm = input(f'¿El valor de A es {A}? (y/n)')
if A_Confirm == 'n':
  while A_Confirm == 'n':
    if A_Confirm == 'n':
      A = float(input('Ingrese el valor de A en notación científica(5E+2) o general(500): '))
      A_Confirm = input(f'¿El valor de A es {A}? (y/n)')
    if A_Confirm == 'y':
      print(f'Valor confirmado')
if A_Confirm == 'y':
 print(f'Valor confirmado')


B = float(input('Ingrese el valor de B en notación científica(5E+2) o general(500): '))

B_Confirm = input(f'¿El valor de B es {B}? (y/n)')
if B_Confirm == 'n':
  while B_Confirm == 'n':
    if B_Confirm == 'n':
      B = float(input('Ingrese el valor de B en notación científica(5E+2) o general(500): '))
      B_Confirm = input(f'¿El valor de B es {B}? (y/n)')
    if B_Confirm == 'y':
      print(f'Valor confirmado')
if B_Confirm == 'y':
 print(f'Valor confirmado')


C = float(input('Ingrese el valor de C en notación científica(5E+2) o general(500): '))

C_Confirm = input(f'¿El valor de C es {C}? (y/n)')
if C_Confirm == 'n':
  while C_Confirm == 'n':
    if C_Confirm == 'n':
      C = float(input('Ingrese el valor de C en notación científica(5E+2) o general(500): '))
      C_Confirm = input(f'¿El valor de C es {C}? (y/n)')
    if C_Confirm == 'y':
      print(f'Valor confirmado')
if C_Confirm == 'y':
 print(f'Valor confirmado')


D = float(input('Ingrese el valor de D en notación científica(5E+2) o general(500): '))

D_Confirm = input(f'¿El valor de D es {D}? (y/n)')
if D_Confirm == 'n':
  while D_Confirm == 'n':
    if D_Confirm == 'n':
      D = float(input('Ingrese el valor de D en notación científica(5E+2) o general(500): '))
      D_Confirm = input(f'¿El valor de D es {D}? (y/n)')
    if D_Confirm == 'y':
      print(f'Valor confirmado')
if D_Confirm == 'y':
 print(f'Valor confirmado')

"""Definiendo Q,T1 y n"""

Q = float(input('Ingrese el valor de Q(J): '))

Q_Confirm = input(f'¿El valor de Q es {Q}? (y/n)')
if Q_Confirm == 'n':
  while Q_Confirm == 'n':
    if Q_Confirm == 'n':
      Q = float(input('Ingrese el valor de Q en notación científica(5E+2) o general(500): '))
      Q_Confirm = input(f'¿El valor de Q es {Q}? (y/n)')
    if Q_Confirm == 'y':
      print(f'Valor confirmado')
if Q_Confirm == 'y':
 print(f'Valor confirmado')


T1 = float(input('Ingrese el valor de T1(K): '))

T1_Confirm = input(f'¿El valor de T1 es {T1}? (y/n)')
if T1_Confirm == 'n':
  while T1_Confirm == 'n':
    if T1_Confirm == 'n':
      T1 = float(input('Ingrese el valor de T1 en notación científica(5E+2) o general(500): '))
      T1_Confirm = input(f'¿El valor de T1 es {T1}? (y/n)')
    if T1_Confirm == 'y':
      print(f'Valor confirmado')
if T1_Confirm == 'y':
 print(f'Valor confirmado')


n = float(input('Ingrese el valor de n(mol): '))

n_Confirm = input(f'¿El valor de n es {n}? (y/n)')
if n_Confirm == 'n':
  while n_Confirm == 'n':
    if n_Confirm == 'n':
      n = float(input('Ingrese el valor de n en notación científica(5E+2) o general(500): '))
      n_Confirm = input(f'¿El valor de n es {n}? (y/n)')
    if n_Confirm == 'y':
      print(f'Valor confirmado')
if n_Confirm == 'y':
 print(f'Valor confirmado')

"""Calculando delta H"""

dH = Q/n
print(f'El valor de delta H es {dH}')

"""Definiendo T2sup"""

#Condicional para que si T2 no es mayor a T1, de un error
T2S = float(input('Ingrese algún valor para T2sup: '))
T2S_Confirm = input(f'¿El valor de T2sup es {T2S}? (y/n)')
if T2S_Confirm == 'n':
  while T2S_Confirm == 'n':
    if T2S_Confirm == 'n':
      T2S = float(input('Ingrese algún valor para T2sup: '))
      T2S_Confirm = input(f'¿El valor de T2S es {T2S}? (y/n)')
    if T2S_Confirm == 'y':
      if T2S < T1:
        print(f'Error, el valor de T2S debe ser mayor al de T1 ({T1})')
      else:
        print(f'Valor confirmado')
if T2S_Confirm == 'y':
      if T2S < T1:
        print(f'Error, el valor de T2S debe ser mayor al de T1 ({T1})')
      else:
        print(f'Valor confirmado')

"""Calculando TMA"""

TMA = (T2S + T1)/2

"""Calculando Cphm"""

Cphm = A + B*TMA + (C/3)*(4*(TMA**2) - T2S*T1) + D*(2*(TMA**3) - TMA*T2S*T1)

"""Calculando T2N"""

T2N = (dH/Cphm) + T1

"""Verificando si |T2N - T2| =< E (0.00001)"""

while abs(T2N-T2S) > 0.0001 :
  if abs(T2N-T2S) > 0.0001 :
    T2S = T2N
    TMA = (T1+T2S)/2
    Cphm = A + B*TMA + (C/3)*(4*(TMA**2) - T2S*T1) + D*(2*(TMA**3) - TMA*T2S*T1)
    T2N = (dH/Cphm) + T1

  if abs(T2N-T2S) <= 0.0001 :
   print(f'El valor de T2 es {T2N}')

input('Presione enter para cerrar el programa')